feat: implemented the extraction of vacancies from the programathor w…
devpleno/junta-vagas pull request #128
Opened 2022-10-31 17:43 UTC by weslenmendes

OBSERVAÇÕES:
==========

- Caso seja necessário dar detalhes para o revisor descreva aqui. Apenas remova esse texto padrão, mas primeiro verifique se leu da as linhas.
- Verificar se está criando o **pull request** para o branch **develop**, pois estão esquecendo é adicionando para o branch **master**.
- Se você adicionar alguma variável de ambiente no arquivo **.env** adicione a chave no arquivo **.env.example** e passa via Discord essas **envs** para o pessoa que está gerenciando o projeto. Exemplo:
    - Se adicionar .env:
    ```
    KEY_TEST=value_teste
    ```
    - Deve adicionar no .env.example: 
    ```
    KEY_TEST=
    ```

2022-11-05 17:31 UTC, tiago123456789 requested changes

2022-11-05 17:31 UTC, tiago123456789 commented on backend/src/crawlers/extractJobsSiteProgramathor.js
> +          title,
@weslenmendes só um detalhes na parte do **title** está vindo o título da vaga é a palavra **NOVA**. Se possível poderia removar a palavra **NOVA** do final do título, pois está deixando um pouco confuso o título da vaga.

A... depois que você cria o arquivo no diretório **crawlers** você precisa registrar ele no arquivo **src/jobs/insertJobsExtractedInDb.js** assim como os outros arquivos que extraem vagas de outros sites, pois quando a tarefa agenda que extrai as vagas dos sites rodarem irá chegar a arquivo registros para pegar as vagas do sites é salva no banco de dados.

2022-11-12 14:42 UTC, weslenmendes commented on backend/src/crawlers/extractJobsSiteProgramathor.js
> +          title,
certo, vou fazer as correções.

2022-11-13 18:10 UTC, tiago123456789 approved these changes

2022-11-13 18:10 UTC, merged