added functions to save jobs and schedule recording in database
devpleno/junta-vagas pull request #46
Opened 2021-12-27 18:31 UTC by wiliansanello

2021-12-27 23:32 UTC, tiago123456789 requested changes

2021-12-27 23:32 UTC, tiago123456789 commented on backend/api/schedule_insert.js
> +rule.hour = 15 //23
Sugestões:
=========

- alterar **rule.hour** de 15 para 23 , pois nós como programadores se deixarmos para depois não fazemos kkkkk
- alterar também **rule.minute** de 07 para 30 também.

Alterações e pontos de atenção:
===============================
- Quando finalizar funcionalidade deve abrir um PR para branch **develop**, assim como explico nas instruções do projeto sobre fluxo do git https://github.com/devpleno/junta-vagas#fluxo-de-git-para-trabalhar-no-projeto
- Criar arquivo **.gitignore** na raiz do projeto é colocar o seguinte conteúdo no arquivo: **node_modules/**
- Você comitou os o diretório **node_modules/** isso é desnecessário, pois quando outro dev 
 for trabalhar basta rodar o comando **npm install** que o npm irá baixar o módulos necessários para aplicação rodar. OBS: link para ajudar a remover o node_modules do github  https://medium.com/@andgomes/git-removendo-arquivos-de-um-reposit%C3%B3rio-7eed699a035f

2021-12-28 13:10 UTC, wiliansanello reviewed
Changes in axios's get request, getJobs function call

2021-12-28 13:30 UTC, wiliansanello commented
The requested changes did done

2021-12-28 13:30 UTC, closed without merging