feat: implemented the functionality to send jobs to a discord channel
devpleno/junta-vagas pull request #85
Opened 2022-06-25 23:00 UTC by weslenmendes

2022-06-27 02:14 UTC, tiago123456789 requested changes

2022-06-27 02:14 UTC, tiago123456789 commented on backend/src/jobs/sendJobsToDiscord.js
> +    jobs.forEach((job) => {
@weslenmendes dessa forma que está fazendo é interessante, mas quando você tiver várias **jobs** por exemplo **20** é baseado no texto que montou para enviar via **webhook** do **Discord** vai erro devido o Discord limita a quantidade de caracteres que você pode enviar. 

Na documentação do Discord menciona que você pode ter um texto com **2000** caracteres. Link da documentação :  https://discord.com/developers/docs/resources/webhook#execute-webhook-jsonform-params

Baseado nessa limitação você pode fazer o seguinte: criar loop passando pelos jobs é fazendo o que está fazendo já, você criar um contador fora do loop que você incrementa depois da parte que monta a mensagem, coloca um if verificando se o contador chegou a **5**  por exemplo se sim enviar a requisição para o Discord, depois de enviar a requisição você limpar a variável que usa para montar o texto e continua o fluxo até finalizar o loop.

A... lembrei quando você enviar muitas requisições para o url de webhook do Discord ele pode retornar um erro com o status 429 que significa que está mandando muitas requisição para api dentro de um período. Então o que eu recomendo é você fazer um esperar 3 segundas depois de cada requisição para evitar esse erro. Exemplo para implementar função que faz esperar um tempo especifico antes de continuar https://gist.github.com/tiago123456789/eff05a37befa09c1c53a156e1b02da37

2022-06-27 02:14 UTC, tiago123456789 commented on backend/src/jobs/sendJobsToDiscord.js
> +      content += `Vaga postada em ${job.postedAt.toLocaleDateString()} na plataforma ${
Creio que não sera necessário essa linha onde informa que onde foi postada a vagas, pois quando a pessoa clicar no link ele vai para a plataforma que postou.

2022-06-27 02:14 UTC, tiago123456789 commented on backend/src/jobs/sendJobsToDiscord.js
> +      content += `Empresa: ${job.company}\n`;
Da linha 35 a 37 creio que é necessário fazer uma verificar para saber se os valores não estão **undefined** pois em alguns cenários pode ocorrer de não conseguir extrair empresa, localização e tecnologias.

2022-07-03 23:56 UTC, weslenmendes commented on backend/src/jobs/sendJobsToDiscord.js
> +    jobs.forEach((job) => {
Ok

2022-07-03 23:57 UTC, weslenmendes commented on backend/src/jobs/sendJobsToDiscord.js
> +      content += `Vaga postada em ${job.postedAt.toLocaleDateString()} na plataforma ${
Certo.

2022-07-03 23:57 UTC, weslenmendes commented on backend/src/jobs/sendJobsToDiscord.js
> +      content += `Empresa: ${job.company}\n`;
Bem observado.

2022-08-20 18:40 UTC, merged